// Represents the data structure for storing insights generated by the AwarenessAgent
class Insight {
    constructor(studentId: string, courseId: string, insightType: string, details: any[]) {
      this.studentId = studentId;
      this.courseId = courseId;
      this.insightType = insightType;
      this.details = details;
    }
  }
  